jobs:
  build:
    # ...
    permissions:
      contents: write
    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1379024
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
