name: Publish Mod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-artifact: ${{ steps.build-artifact.outputs.path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      
      - name: runData with Gradle
        run: ./gradlew runDatagen

      - name: Build with Gradle
        run: ./gradlew build


      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/libs/*.jar

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build/libs

      - name: Extract version from JAR filename
        id: get_version
        run: |
          jar=$(ls ./build/libs/*.jar | head -n1)
          base=$(basename "$jar" .jar)
          version="${base##*-}"
          version=${version//+/-}
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "::set-output name=name::$version"
          echo $version



      - name: Publish to CurseForge and Modrinth + Release to Github.
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1379091
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          modrinth-id: d3ySFbJG
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/libs/*.jar
          name: Moderate Copper ${{ steps.get_version.outputs.name }}
